/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "buoy_data.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WindData, WindData, AUTO)


PB_BIND(AirData, AirData, AUTO)


PB_BIND(CurrentData, CurrentData, AUTO)


PB_BIND(WaveData, WaveData, AUTO)


PB_BIND(Telemetry, Telemetry, AUTO)


PB_BIND(BuoyData, BuoyData, AUTO)



